# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        acme.flysystem_adapter:
            awss3v3:
                client: Aws\S3\S3ClientInterface
                bucket: '%env(AWS_S3_BUCKET)%'
    filesystems:
        acme:
            adapter: acme.flysystem_adapter
            alias: League\Flysystem\FilesystemInterface
